config/routes.rb
OzpinGen::Application.routes.draw do
  root :to => "home#index"
  get '/search', :to =>'home#search'
  get '/cities/:id' => 'home#show', :as => 'cities'

  get '/story/new' => 'home#new', :as => 'new_story'
  get '/contact/new' => 'home#contact', :as => 'new_contact'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def search
    redirect_to cities_url(params[:city])
  end

  def show
    @city = params[:id].titleize
  end

  def new

  end

  def contact

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.slim
.row
	.col-md-2
	.col-md-8
		.jumbotron
			h1 Contact your local politicians.


		    p It looks like your city could use some improvement. Why not contact your local politicians to see if we can improve this situation.

	    	== form_tag '/search', id: 'search', class: 'form-inline', method: :get do
	    		
				textarea#story_text.form-control placeholder='Share your success story...' name='story' rows='4'

				button.btn.btn-lg.btn-success type='submit'
					| Submit
   	.col-md-2

app/views/home/index.html.slim
.row
	.col-md-2
	.col-md-8
		.jumbotron
			h1.logo CityScore.<span>io</span>
			p Your guide to energy efficient cities
	.col-md-2

.row
	.col-md-2
	.col-md-8
		== form_tag '/search', id: 'search', class: 'form-inline', method: :get do
			.form-group
				input#search_input.form-control.input-lg placeholder='Search for a city...' name='city'
			button.col-md-offset-1.btn.btn-lg.btn-success type='submit'
				| Search
	.col-md-2

app/views/home/new.html.slim
.row
	.col-md-2
	.col-md-8
		.jumbotron
			h1 Share your story

	    	p Congratulation, you live in one of the top cities. Share your success stories so others know what it takes to succeed.

	    	== form_tag '/search', id: 'search', class: 'form-inline', method: :get do
	    		
				textarea#story_text.form-control placeholder='Share your success story...' name='story' rows='4'

				button.btn.btn-lg.btn-success type='submit'
					| Submit
   	.col-md-2

app/views/home/show.html.slim
.row
	.col-md-2
	.col-md-8
		.jumbotron
			h1= @city
			.badge
  				.dotted
  					- if @city == 'San Diego'
	    				.bubble data-icon='95'
	    			- else
	    				.bubble data-icon='55'


	    	- if @city == 'San Diego'
		    	p Congratulation, you live in one of the top cities. Share your success stories so others know what it takes to succeed.	
		    	= link_to 'Share Your Story', new_story_url, class: 'button btn btn-primary'

		   	- else
		    	p It looks like your city could use some improvement. Why not contact your local politicians to see if we can improve this situation.
		    	= link_to 'Contact Your Representatives', new_contact_url, class: 'button btn btn-primary'


   	.col-md-2

app/views/layouts/_logo.html.slim
.row
	.col-md-2
	.col-md-8
		#logo
			h1 = link_to raw('CityScore.<span>io</span>'), root_url
   	.col-md-2

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name == :notice ? "success" : "danger"}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Ozpin Gen'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Ozpin Gen'}"
    == stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => true
    == javascript_include_tag "application", "data-turbolinks-track" => true
    == csrf_meta_tags
    link href='http://fonts.googleapis.com/css?family=Lora|PT+Sans:400,700|Bitter' rel='stylesheet' type='text/css'
  body
    div class='container'
      header
      main[role="main"]
        == render 'layouts/messages'
        == render 'layouts/logo' unless params[:action] == 'index'
        == yield

app/views/layouts/logo.html.slim
#logo
	h1.logo CityScore.<span>io</span>